'use strict';
module.exports = (sequelize, type) => {
    const loan_guarantor = sequelize.define('loan_guarantor', {
        id: {
            type: type.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
       
        g_f_name: type.STRING,
        g_email: type.STRING,
        g_fathers_name: type.STRING,
        g_phone_no: type.STRING,
        g_address: type.STRING,
        g_occupation: type.STRING,
        g_dob: { type: 'DATE' },
        g_gender: type.STRING,
        g_maried: type.STRING,
        g_resident: type.STRING,
        g_house_owner: type.STRING,
        g_house_owner_phone: type.STRING,
        g_stay_since: { type: 'DATE' },
        g_edu: type.STRING,
        g_temp_address: type.STRING,
        g_Depend_family: type.STRING,
        g_ac_no: type.STRING,
        g_br_name: type.STRING,
        g_scheme: type.STRING,
        g_start: { type: 'DATE' },
        g_customer_id: type.STRING,
        g_end: { type: 'DATE' },
        g_total_amnt: type.STRING,
        g_csp_msp: type.STRING,
        g_adharNo: type.STRING,
        g_panNo: type.STRING,
        g_employee_type: type.STRING,
        g_emp_emp_type: type.STRING,
        g_emp_mode_salary: type.STRING,
        g_emp_net_salary: type.STRING,
        g_emp_othr_incm: type.STRING,
        g_self_bsns_type: type.STRING,
        g_self_bsns_start: { type: 'DATE' },
        g_self_prfsn: type.STRING,
        g_self_practice_start: { type: 'DATE' },
        g_self_anual_incm: type.STRING,
        g_self_anual_expnd: type.STRING,
        g_self_net_income: type.STRING,
        g_LA_name: type.STRING,
        g_LA_loan_amnt: type.STRING,
        g_LA_emi: type.STRING,
        g_LA_balance: type.STRING,
        g_LA_startDate: { type: 'DATE' },
        g_LA_name1: type.STRING,
        g_LA_loan_amnt1: type.STRING,
        g_LA_emi1: type.STRING,
        g_LA_balance1: type.STRING,
        g_LA_startDate1: { type: 'DATE' },
        g_LA_name2: type.STRING,
        g_LA_loan_amnt2: type.STRING,
        g_LA_emi2: type.STRING,
        g_LA_balance2: type.STRING,
        g_LA_startDate2: { type: 'DATE' },
        g_LA_name3: type.STRING,
        g_LA_loan_amnt3: type.STRING,
        g_LA_emi3: type.STRING,
        g_LA_balance3: type.STRING,
        g_LA_startDate3: { type: 'DATE' },
        g_LA_name4: type.STRING,
        g_LA_loan_amnt4: type.STRING,
        g_LA_emi4: type.STRING,
        g_LA_balance4: type.STRING,
        g_LA_startDate4: { type: 'DATE' },
        g_photo: type.STRING,
        g_id_proof: type.STRING,
        g_sign: type.STRING,
        g_address_proof: type.STRING,
        g_FS: type.STRING,
    }, {});
    loan_guarantor.associate = function(models) {
        // associations can be defined here
        loan_guarantor.belongsTo(models.loans)
    };
    return loan_guarantor;
};